# Generated by Django 4.1.7 on 2023-08-08 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_namespace_namespace_unique_user_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='chatdatasource',
            old_name='last_update',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='chatdatasource',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='namespace',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='FileNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.file')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.namespace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='filenamespace',
            constraint=models.UniqueConstraint(fields=('file_name', 'namespace'), name='unique_file_namespace'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('user_id', 'file_name'), name='unique_user_file_name'),
        ),
    ]
