# Generated by Django 4.1.7 on 2023-08-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_file_rename_last_update_chatdatasource_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenamespace',
            old_name='file_name',
            new_name='file',
        ),
    ]
