# Generated by Django 4.1.7 on 2023-08-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_file_name_filenamespace_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filenamespace',
            name='unique_file_namespace',
        ),
        migrations.AddConstraint(
            model_name='filenamespace',
            constraint=models.UniqueConstraint(fields=('file', 'namespace'), name='unique_file_namespace'),
        ),
    ]
