# Generated by Django 4.1.7 on 2023-08-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_filenamespace_unique_file_namespace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdatasource',
            name='user',
        ),
    ]
