# Generated by Django 4.1.7 on 2023-08-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatdatasource_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatdatasource',
            name='chat_data_source_pk',
        ),
        migrations.AddConstraint(
            model_name='chatdatasource',
            constraint=models.UniqueConstraint(['file_name', 'namespace'], name='chat_data_source_pk'),
        ),
    ]
