# Generated by Django 4.1.7 on 2023-08-10 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_chatdatasource_chat_data_source_pk_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatdatasource',
            name='chat_data_source_pk',
        ),
        migrations.AddField(
            model_name='chatdatasource',
            name='user',
            field=models.ForeignKey(default=uuid.UUID('53c8d045-e3ec-4c42-a2e4-1c5a3d511f9b'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatdatasource',
            constraint=models.UniqueConstraint(fields=('user_id', 'file_name', 'namespace'), name='chat_data_source_pk'),
        ),
    ]
