# Generated by Django 4.1.7 on 2023-08-10 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_remove_chatdatasource_chat_data_source_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdatasource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
