# Generated by Django 4.1.7 on 2023-08-08 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('48f8ad12-2085-419a-a086-ca0f816db439')),
        ),
    ]
