# Generated by Django 4.1.7 on 2023-08-08 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2565fa6e-45d3-40b9-94db-6a1fbc4380e5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
