# Generated by Django 4.1.7 on 2023-08-08 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('3242bf18-d057-4a01-be8c-29dc9c1d4d5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
