# Generated by Django 4.1.7 on 2023-08-09 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f2bcb316-6c92-4f7a-9d49-9bda7c23a63b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
