# Generated by Django 4.1.7 on 2023-08-10 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0f0fd638-5925-4673-9118-1b19b0426123'), editable=False, primary_key=True, serialize=False),
        ),
    ]
