# Generated by Django 4.1.7 on 2023-08-10 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('06187818-7e35-4dd8-928f-44ceffbd4c53'), editable=False, primary_key=True, serialize=False),
        ),
    ]
