# Generated by Django 4.1.7 on 2023-08-10 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('434fb6c7-f023-4724-99af-866b8af47354'), editable=False, primary_key=True, serialize=False),
        ),
    ]
