# Generated by Django 4.1.7 on 2023-08-10 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('b4e94721-55a5-4f7a-adcd-2ffb5a0afad0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
