# Generated by Django 4.1.7 on 2023-08-10 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0204f31e-b372-4a42-993b-f2c5bb64b384'), editable=False, primary_key=True, serialize=False),
        ),
    ]
