# Generated by Django 4.1.7 on 2023-08-10 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('27bfcea4-8e08-4a88-b854-dec23d3fae77'), editable=False, primary_key=True, serialize=False),
        ),
    ]
