# Generated by Django 4.1.7 on 2023-08-10 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2c56d96d-ddf7-4a92-b756-6c6bf6a91fae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
