# Generated by Django 4.1.7 on 2023-08-10 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('d3a1ef2e-ceac-4548-95dd-337aebc73d8b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
